LPARAMETERS lpAccion

lpAccion=IIF(EMPTY(lpAccion),'NADA',ALLTRIM(UPPER(lpAccion)))

IF lpAccion<>'NADA'
	CLOSE TABLES all
	_path=GETDIR('','Ingrese directorio de tablas','Tablas Para Gestion de Triggers')
	SET DEFAULT TO &_path
ENDIF 

DO CASE 
	CASE lpAccion='AT'
		*Script para agregar los TRIGGER a las tablas
		USE articulo_univoco1 EXCLUSIVE
		CREATE TRIGGER ON articulo_univoco1 FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON articulo_univoco1 FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON articulo_univoco1 FOR DELETE AS SINCRODELETE()
		USE

		USE clientes EXCLUSIVE
		CREATE TRIGGER ON clientes FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON clientes FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON clientes FOR DELETE AS SINCRODELETE()
		USE

		USE colores EXCLUSIVE
		CREATE TRIGGER ON colores FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON colores FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON colores FOR DELETE AS SINCRODELETE()
		USE 

		USE depósitos EXCLUSIVE
		CREATE TRIGGER ON depósitos FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON depósitos FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON depósitos FOR DELETE AS SINCRODELETE()
		USE

		USE empleados_cliente EXCLUSIVE
		CREATE TRIGGER ON empleados_cliente FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON empleados_cliente FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON empleados_cliente FOR DELETE AS SINCRODELETE()
		USE

		USE rubro EXCLUSIVE
		CREATE TRIGGER ON rubro FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON rubro FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON rubro FOR DELETE AS SINCRODELETE()
		USE

		USE stock1 EXCLUSIVE
		CREATE TRIGGER ON stock1 FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON stock1 FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON stock1 FOR DELETE AS SINCRODELETE()
		USE

		USE subrubro EXCLUSIVE
		CREATE TRIGGER ON subrubro FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON subrubro FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON subrubro FOR DELETE AS SINCRODELETE()
		USE

		USE unidmedida EXCLUSIVE
		CREATE TRIGGER ON unidmedida FOR INSERT AS SINCROINSERT()
		CREATE TRIGGER ON unidmedida FOR UPDATE AS SINCROUPDATE()
		CREATE TRIGGER ON unidmedida FOR DELETE AS SINCRODELETE()
		USE
		MESSAGEBOX('Se Agregaron los Triggers a las Tablas',64,'Genial !!')
	CASE lpAccion='BT'
		*Script para BORRAR los TRIGGER a las tablas
		USE articulo_univoco1 EXCLUSIVE
		DELETE TRIGGER ON articulo_univoco1 FOR INSERT 
		DELETE TRIGGER ON articulo_univoco1 FOR UPDATE 
		DELETE TRIGGER ON articulo_univoco1 FOR DELETE 
		USE

		USE clientes EXCLUSIVE
		DELETE TRIGGER ON clientes FOR INSERT
		DELETE TRIGGER ON clientes FOR UPDATE
		DELETE TRIGGER ON clientes FOR DELETE
		USE

		USE colores EXCLUSIVE
		DELETE TRIGGER ON colores FOR INSERT
		DELETE TRIGGER ON colores FOR UPDATE
		DELETE TRIGGER ON colores FOR DELETE
		USE 

		USE depósitos EXCLUSIVE
		DELETE TRIGGER ON depósitos FOR INSERT
		DELETE TRIGGER ON depósitos FOR UPDATE
		DELETE TRIGGER ON depósitos FOR DELETE
		USE

		USE empleados_cliente EXCLUSIVE
		DELETE TRIGGER ON empleados_cliente FOR INSERT
		DELETE TRIGGER ON empleados_cliente FOR UPDATE
		DELETE TRIGGER ON empleados_cliente FOR DELETE
		USE

		USE rubro EXCLUSIVE
		DELETE TRIGGER ON rubro FOR INSERT
		DELETE TRIGGER ON rubro FOR UPDATE
		DELETE TRIGGER ON rubro FOR DELETE
		USE

		USE stock1 EXCLUSIVE
		DELETE TRIGGER ON stock1 FOR INSERT
		DELETE TRIGGER ON stock1 FOR UPDATE
		DELETE TRIGGER ON stock1 FOR DELETE
		USE

		USE subrubro EXCLUSIVE
		DELETE TRIGGER ON subrubro FOR INSERT
		DELETE TRIGGER ON subrubro FOR UPDATE
		DELETE TRIGGER ON subrubro FOR DELETE
		USE

		USE unidmedida EXCLUSIVE
		DELETE TRIGGER ON unidmedida FOR INSERT
		DELETE TRIGGER ON unidmedida FOR UPDATE
		DELETE TRIGGER ON unidmedida FOR DELETE
		USE
		MESSAGEBOX('Se Borraron los Triggers de las Tablas',64,'Genial !!')
	OTHERWISE 
		MESSAGEBOX("FORMA CORRECTA"+CHR(13)+CHR(13);
				+"SetTriggers WITH 'AT' - AGREGA Triggers a las Tablas"+CHR(13);
				+CHR(13);
				+"SetTriggers WITH 'BT' - BORRA Triggers de las Tablas"+CHR(13),;
				0+64,'FORMA DE USO')
ENDCASE 